# Generated by Django 2.2.5 on 2019-09-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('hp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('defense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spirit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
