# Generated by Django 2.2.5 on 2019-09-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='rarity',
            field=models.IntegerField(default=0),
        ),
    ]
