# Generated by Django 2.2.5 on 2019-09-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0003_auto_20190912_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=50)),
                ('hp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('defense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spirit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hp_porc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp_porc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attack_porc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magic_porc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('defense_porc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spirit_porc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
