# Generated by Django 2.2.5 on 2019-09-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0004_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('hp_porc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mp_porc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attack_porc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('magic_porc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('defense_porc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spirit_porc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='attack_porc',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='defense_porc',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='hp_porc',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='magic_porc',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='mp_porc',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='spirit_porc',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='attack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='defense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='hp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='magic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='mp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='spirit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
