# Generated by Django 2.2.5 on 2019-09-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0005_auto_20190912_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='category',
            field=models.CharField(default='rod', max_length=50),
            preserve_default=False,
        ),
    ]
