# Generated by Django 2.2.5 on 2019-09-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0006_weapon_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('hp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attack', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('magic', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('defense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spirit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameModel(
            old_name='Hero',
            new_name='Unit',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ffbe_app.Item'),
        ),
        migrations.AddField(
            model_name='ability',
            name='item',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='ffbe_app.Item'),
            preserve_default=False,
        ),
    ]
