# Generated by Django 2.2.5 on 2019-09-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0007_auto_20190913_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ability',
            field=models.ManyToManyField(related_name='_equipment_ability_+', to='ffbe_app.Ability'),
        ),
    ]
