# Generated by Django 2.2.5 on 2019-09-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffbe_app', '0008_equipment_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ability',
            field=models.ManyToManyField(related_name='_unit_ability_+', to='ffbe_app.Ability'),
        ),
    ]
